-- AlterTable
ALTER TABLE `orders` MODIFY `status` ENUM('PENDING_PAYMENT', 'PAID', 'CONFIRMED', 'PACKING', 'SHIPPING', 'DELIVERED', 'CANCELLED', 'RETURN_REQUESTED', 'RETURNED', 'REFUNDED', 'NOT_FOUND_ORDER_CODE') NULL,
    MODIFY `payment_status` ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PAYMENT_SHORTFALL', 'PAYMENT_OVERAGE', 'PARTIAL_REFUND', 'EXPIRED', 'NOT_FOUND_ORDER_CODE') NULL;

-- AlterTable
ALTER TABLE `payment_intents` MODIFY `status` ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PAYMENT_SHORTFALL', 'PAYMENT_OVERAGE', 'PARTIAL_REFUND', 'EXPIRED', 'NOT_FOUND_ORDER_CODE') NULL;

-- AlterTable
ALTER TABLE `payment_transactions` MODIFY `status` ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PAYMENT_SHORTFALL', 'PAYMENT_OVERAGE', 'PARTIAL_REFUND', 'EXPIRED', 'NOT_FOUND_ORDER_CODE') NULL;
