services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /docker/mysql_data:/var/lib/mysql
    ports:
      - '127.0.0.1:3308:3306'
  redis:
    image: redis:7.2
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - /docker/redis_data:/data
  redis-insight:
    image: redislabs/redisinsight:2.6.0
    restart: unless-stopped
    ports:
      - '5540:5540'

volumes:
  mysql_data:
  redis_data:
