services:
  bookstore-api:
    image: ghcr.io/delusss2345/bookstore-api:latest
    restart: unless-stopped
    container_name: bookstore-api
    env_file:
      - .env
    ports:
      - '3301:3301'

volumes:
networks:
  book-store-network:
    driver: bridge
