services:
  mysql:
    image: mysql:8.4
    restart: always
    env_file:
      - .env
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3307:3306'

    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 20
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - .env
    command: ['sh', '-c', 'redis-server --requirepass "$${REDIS_PASSWORD}"']
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis_data:/data

  app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - '127.0.0.1:3301:3301'

volumes:
  mysql_data:
  redis_data:
