name: Deploy Production

on:
  workflow_dispatch:
  push:
    branches:
      - production

concurrency:
  group: production-workflows-dev
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      packages: read

    if: github.ref == 'refs/heads/production'

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.1
        env:
          GHCR_TOKEN: ${{ github.token }}
          GHCR_USER: ${{ github.actor }}
          IMAGE_NAME: ghcr.io/${{ github.repository }}:latest
        with:
          debug: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          envs: GHCR_TOKEN,GHCR_USER,IMAGE_NAME
          script: |
            cd api/book_store 

            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
            docker pull "$IMAGE_NAME"
            docker compose up -d --force-recreate
            docker image prune -a -f
            docker exec bookstore-api npx prisma migrate deploy
