name: Deploy Production
on:
  workflow_dispatch:
  push:
    branches:
      - production
concurrency:
  group: production-workflows-dev
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        env:
          GHCR_TOKEN: ${{ github.token }}
          GHCR_USER: ${{ github.actor }}
          IMAGE_NAME: ghcr.io/${{ github.repository }}/book-store-backend:latest
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.PORT }}
          envs: GHCR_TOKEN,GHCR_USER,IMAGE_NAME
          script: |
            cd threads-api

            eco "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
            docker pull "$IMAGE_NAME"
